// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRyMrpk9z2Jm7I239SbqxsqiHLCKEEew',
    appId: '1:138853979633:web:1f3c40d2fc84d3254c6050',
    messagingSenderId: '138853979633',
    projectId: 'easlearn-51990',
    authDomain: 'easlearn-51990.firebaseapp.com',
    storageBucket: 'easlearn-51990.firebasestorage.app',
    measurementId: 'G-0X9DYKJ1NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWtaWhmBxfiKKLWUear6-srqyN2noCAc',
    appId: '1:138853979633:android:527a7456f1032ebe4c6050',
    messagingSenderId: '138853979633',
    projectId: 'easlearn-51990',
    storageBucket: 'easlearn-51990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-lLx90F1XmlOjFjf-572hY36wLvs7cY',
    appId: '1:138853979633:ios:86cf1c1ab5950c9b4c6050',
    messagingSenderId: '138853979633',
    projectId: 'easlearn-51990',
    storageBucket: 'easlearn-51990.firebasestorage.app',
    iosClientId: '138853979633-e61fivp4skq5mjus9h076gadcn4m5o1a.apps.googleusercontent.com',
    iosBundleId: 'com.edupulse.edupulseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-lLx90F1XmlOjFjf-572hY36wLvs7cY',
    appId: '1:138853979633:ios:86cf1c1ab5950c9b4c6050',
    messagingSenderId: '138853979633',
    projectId: 'easlearn-51990',
    storageBucket: 'easlearn-51990.firebasestorage.app',
    iosClientId: '138853979633-e61fivp4skq5mjus9h076gadcn4m5o1a.apps.googleusercontent.com',
    iosBundleId: 'com.edupulse.edupulseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuRyMrpk9z2Jm7I239SbqxsqiHLCKEEew',
    appId: '1:138853979633:web:b2fb5792f5ca987c4c6050',
    messagingSenderId: '138853979633',
    projectId: 'easlearn-51990',
    authDomain: 'easlearn-51990.firebaseapp.com',
    storageBucket: 'easlearn-51990.firebasestorage.app',
    measurementId: 'G-J2B20BXHFE',
  );

}