// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3yR2POGK4kSoe_xKAHLEmfTM84HgGu4',
    appId: '1:757004652724:web:17ca9f7925ebdb684b47e1',
    messagingSenderId: '757004652724',
    projectId: 'project-abcfc',
    authDomain: 'project-abcfc.firebaseapp.com',
    storageBucket: 'project-abcfc.firebasestorage.app',
    measurementId: 'G-S4HH8KHPP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDGUn_059WKg_aNh8jG2QYu5UmSY48pg',
    appId: '1:757004652724:android:b2c8b626fdeb3e7c4b47e1',
    messagingSenderId: '757004652724',
    projectId: 'project-abcfc',
    storageBucket: 'project-abcfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmMV9gkFYhFINHCR541m3-FOgkkR9Jds',
    appId: '1:757004652724:ios:a1a9f4014364becd4b47e1',
    messagingSenderId: '757004652724',
    projectId: 'project-abcfc',
    storageBucket: 'project-abcfc.firebasestorage.app',
    iosBundleId: 'com.edupulse.edupulseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQmMV9gkFYhFINHCR541m3-FOgkkR9Jds',
    appId: '1:757004652724:ios:a1a9f4014364becd4b47e1',
    messagingSenderId: '757004652724',
    projectId: 'project-abcfc',
    storageBucket: 'project-abcfc.firebasestorage.app',
    iosBundleId: 'com.edupulse.edupulseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3yR2POGK4kSoe_xKAHLEmfTM84HgGu4',
    appId: '1:757004652724:web:a01bc6a7d5ed31c34b47e1',
    messagingSenderId: '757004652724',
    projectId: 'project-abcfc',
    authDomain: 'project-abcfc.firebaseapp.com',
    storageBucket: 'project-abcfc.firebasestorage.app',
    measurementId: 'G-JQ9R6KS6NR',
  );
}
